"""add indexes and unique constraints

Revision ID: bec45a417afc
Revises: e0aca6657f8c
Create Date: 2026-02-17 02:19:28.231829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec45a417afc'
down_revision: Union[str, None] = 'e0aca6657f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_job_matches_score', 'job_matches', ['match_score'], unique=False)
    op.create_index('ix_job_matches_status', 'job_matches', ['status'], unique=False)
    op.create_index('ix_jobs_is_active', 'jobs', ['is_active'], unique=False)
    op.create_index('ix_jobs_scraped_at', 'jobs', ['scraped_at'], unique=False)
    op.create_unique_constraint('uix_source_external_id', 'jobs', ['source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_source_external_id', 'jobs', type_='unique')
    op.drop_index('ix_jobs_scraped_at', table_name='jobs')
    op.drop_index('ix_jobs_is_active', table_name='jobs')
    op.drop_index('ix_job_matches_status', table_name='job_matches')
    op.drop_index('ix_job_matches_score', table_name='job_matches')
    # ### end Alembic commands ###
